### ISSUE TITLE
An error occurred while installing nokogiri (1.6.4.1), and Bundler cannot continue.

### ISSUE THREAD

**Issue by intelligence** [gael-ian/vagrant-bindfs#19]
Getting this error when trying to install this. Tried to install nokogiri on my own and found errors pointing me to this http://stackoverflow.com/questions/22703393/clang-error-unknown-argument-mno-fused-madd-wunused-command-line-argumen

So got nokogiri installed, but when trying to install again it still throws me this..

**Comment by oflannabhra** [comment]
I'm coming across a similar issue, @intelligence . I realize this might not be vagrant-bindfs specific, but how did you resolve it?
