### ISSUE TITLE
Fuse kernel module seems to be not loaded

### ISSUE THREAD

**Issue by brunobatista** [gael-ian/vagrant-bindfs#20]
Hello, I get yellow info when start up my VM, have any fix for it?

```bash
==> default: Bindfs seems to not be installed on the virtual machine
==> default: Fuse kernel module seems to be not loaded, trying to load it
```

Thanks.

**Comment by brunobatista** [comment]
I tested with OS X 10.10 and Windows 8.1, both show same message.

![erro](https://cloud.githubusercontent.com/assets/441774/5661478/5b160418-9713-11e4-8b90-232e1c17d344.gif)

The gif take time to finish. Be patient and wait at the end. Thanks!

**Comment by gael-ian** [comment]
Which OS runs inside your VM ?

**Comment by JulianVolodia** [comment]
I see the same line.

uname -a
> 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
uname -a (on vagrant)
> Linux wheezy 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u1 x86_64 GNU/Linux

I turn on module fuse on real machine, nfs-server and bindfs plugin real machine.

What should I do?

**Comment by callerc1** [comment]
Hi, Im getting the same issue. Running ubuntu 14.04 on VM.

**Comment by brunobatista** [comment]
OS X 10.10

**Comment by JulianVolodia** [comment]
I put line:
> fuse
in the `/etc/modules` on VM and it disappear.

But I didn't notice very high jump of performance... How to tweak it up using bindfs + nfs? Any suggestion?

**Comment by gael-ian** [comment]
vagrant-bindfs 0.3.4 should fix this issue.
After the upgrade, the warning about fuse kernel module should disappear from the 2nd vagrant up.

@JulianVolodia : Sorry but I have any idea on how to tweak that. Thanks for helping me to understood this issue.

**Comment by brunobatista** [comment]
Thanks @gael-ian :+1:

**Comment by JulianVolodia** [comment]
it's not the issue, really... because vagrant try to load modules (for ex. `modprobe fuse`) and it just work. Yellow lines are only the warings, not critical.

Best regards! I glad that I helped.

**Comment by JulianVolodia** [comment]
PS I think that you should not add any changes to /etc/modules, cause when somebody will not use this plugin it will also be loaded! (causing the memory and cpu time usage)

**Comment by gael-ian** [comment]
@JulianVolodia vagrant-bindfs 0.4.0 does not add anything to /etc/modules anymore. Fuse detection on Ubuntu is now based on the existence of /dev/fuse (which is also available on other OS but I think mod detection is a cleaner way).

**Comment by JulianVolodia** [comment]
@gael-ian sorry I have misunderstood last comment.
