### ISSUE TITLE
Missing wget is not installed

### ISSUE THREAD

**Issue by rpsu** [gael-ian/vagrant-bindfs#27]
We're using a Red hat -based distro that seems to not have wget installed (vagrant box scientific65_x86_64_minimal, distro https://www.scientificlinux.org/). 

Installing bindfs fails with fresh vagrant due to missing wget. Would it be okay to add wget to yum package list in 
  vagrant-bindfs/lib/vagrant-bindfs/cap/redhat/install_bindfs.rb:14

                  comm.sudo("yum -y install fuse fuse-devel gcc wget")

?

**Comment by gael-ian** [comment]
Sorry for being so long to reply.

There's no problem to add wget as a requirement on Red Hat. I'll try to add it quickly and publish a new release in the run.

**Comment by gael-ian** [comment]
Thanks to you, Kalle. I totally forgot this issue till your PR.
0.4.1 is available with the fix.
