### ISSUE TITLE
Warning Message from Vagrant

### ISSUE THREAD

**Issue by jeanpierreb** [gael-ian/vagrant-bindfs#28]
I get a message when creating the vm
```
=> web: Bindfs seems to not be installed on the virtual machine
```
Is this something I should be concerned about? Everything seems to be working on my vm but that message concerns me because a simple `which bidnfs` reveals that it is infact installed on the box I'm using. Incidentally the default 'ubuntu/trusty64'

**Comment by gael-ian** [comment]
On Ubuntu and other supported Linux flavour, you should see this message only at first boot. The plugin will try to install bindfs on the virtual machine just after and, on Ubuntu, should succeed.

If everything seems to work on your virtual machine once booted and accessed, all is fine.
If the message appears on subsequent boots, we may have a problem.

**Comment by jeanpierreb** [comment]
I ran `vagrant halt` then `vagrant up` and it seems fine.
