### ISSUE TITLE
chmod() only applies on the host

### ISSUE THREAD

**Issue by ulrichsg** [gael-ian/vagrant-bindfs#29]
I have a Vagrant box (running Debian Wheezy) with vagrant-bindfs on an Ubuntu host. Here's a curious issue I'm experiencing:

```
vagrant@twx:/www/twx/logs$ ls -la debug.log
-rw-r--r-- 1 vagrant vagrant 77941 May 27 13:15 debug.log
vagrant@twx:/www/twx/logs$ chmod a+w debug.log
vagrant@twx:/www/twx/logs$ ls -la debug.log
-rw-r--r-- 1 vagrant vagrant 77941 May 27 13:15 debug.log
```

The chmod seems to have no effect at all. However, on the *host* filesystem the file now has 666 permissions!

I can change permissions of files outside the synced folder (eg. in /tmp) just fine. Any ideas?

**Comment by gael-ian** [comment]
Hello,

Bind commands are build with some default options, including some permissions setup (See [line 75](https://github.com/gael-ian/vagrant-bindfs/blob/master/lib/vagrant-bindfs/command.rb#L75)).

Can you test to set this option to `nil` and retry chmod ?

**Comment by ulrichsg** [comment]
That works, thank you very much :)
