### ISSUE TITLE
bindfs failing on a VM that has not yet been provisioned

### ISSUE THREAD

**Issue by mhaylock** [gael-ian/vagrant-bindfs#31]
I want to use bindfs with a user and group that does not exist on the VM until after it's been provisioned. bindfs fails during the initial `vagrant up` due to the user not existing and prevents the provisioning from completing.

Do you think it would be practical to modify the plugin to optionally handle this scenario?

**Comment by mhaylock** [comment]
I've added a PR that addresses this problem for my purposes: #32

**Comment by gael-ian** [comment]
Your PR is merged and now there is a new release of the plugin that let you choose when a folder is binded, either after folder syncing (as usual) or after provisioning by using a new :after option the bind_folder method now supports.

Hope it helps you and thanks for contributing.

**Comment by mhaylock** [comment]
@gael-ian apologies for the delayed response but 0.4.2 is working great with the new `:after` option - thank you!
