### ISSUE TITLE
Bind folder name cannot contain the word "bindfs"

### ISSUE THREAD

**Issue by lmeurs** [gael-ian/vagrant-bindfs#33]
At first I used the following setting:

    config.bindfs.bind_folder /var/vagrant-bindfs/my/folder /my/folder

The mounts did not succeed and I received warnings when starting Vagrant:

    There's already a bindfs mount to destination /my/folder

This appeared to be due to `/var/vagrant-bindfs/my/folder` containing the word "bindfs", my workaround was using a different folder name, ie. `/var/vagrant-nfs/my/folder`.

One solution is to change the first grep from https://github.com/gael-ian/vagrant-bindfs/blob/5085b6e167038451fb4e721d7c51481e76c7a57f/lib/vagrant-bindfs/bind.rb#L65 from:

    if @machine.communicate.test("mount | grep bindfs | grep #{command.destination}")

into ie.:

    if @machine.communicate.test("mount | grep "^bindfs" | grep #{command.destination}")

Now only lines are grepped *starting* with "bindfs", though I do not know whether this works on Linux distributions other than my Ubuntu 14.04.

**Comment by gael-ian** [comment]
The new 0.4.3 release has just been pushed with a fix really close to the one you propose. Using regexp pattern with grep should not create problem on any distro as it's a standard and documented option.

Thanks for your contribution.
