### ISSUE TITLE
enabling multithreaded doesn't work

### ISSUE THREAD

**Issue by merpmerp** [gael-ian/vagrant-bindfs#38]
Enabling the multithreaded option for bindfs doesn't work:
Vagrant Config Snippet:
    local_ebweb1.bindfs.bind_folder "/mnt/src", "/src",
        :"multithreaded" => true,
        :"chown-ignore" => true,
        :"chgrp-ignore" => true,
        :"chmod-ignore" => true,
        :perms => "u=rwx:g=rwx:o=rx",
        :user => 1500,
        :group => 1500

Running process in linux guest: (no --multithreaded option)
bindfs --perms=u=rwx:g=rwx:o=rx --chown-ignore --chgrp-ignore --chmod-ignore --user=1500 --group=1500 /mnt/src /src

**Comment by gael-ian** [comment]
Hello

Which version of bindfs is installed inside your VM ?

**Comment by merpmerp** [comment]
1.13.0

**Comment by merpmerp** [comment]
my bindfs binary is in /usr/local/bin, sudo doesn't seem to find it by default
perhaps thats whats is causing "bindfs_version_lower_than" to strip multithreaded out?


$ sudo bindfs --version | cut -d" " -f2
sudo: bindfs: command not found

$ sudo -i bindfs --version | cut -d" " -f2
1.13.0

**Comment by gael-ian** [comment]
This may be a reason, I can't check how `Gem::Version.new` interprets a non-numeric release number for the moment. How do you install bindfs ?

You can add a `local_ebweb1.bindfs.debug = true` to your Vagrantfile and relaunch your VM.
This will output every bindfs commands, so you can ensure all your options are present, try to run it yourself once logged in the VM and may get a more complete error message.

**Comment by merpmerp** [comment]
==> local_ebweb1: Fuse kernel module seems to be not loaded, trying to load it
==> local_ebweb1: Creating bind mounts for selected devices
==> local_ebweb1: Creating bind mount from /mnt/src to /src
==> local_ebweb1: bindfs --perms=u=rwx:g=rwx:o=rx --chown-ignore --chgrp-ignore --chmod-ignore -o noatime --user=1500 --group=1500 /mnt/src /src
==> local_ebweb1: Creating bind mount from /mnt/resources to /var/resources
==> local_ebweb1: bindfs --perms=u=rwx:g=rwx:o=rx --chown-ignore --chgrp-ignore --chmod-ignore -o noatime --user=1500 --group=1500 /mnt/resources /var/resources

**Comment by merpmerp** [comment]
I've created a symlink to /usr/local/bin/bindfs in /bin so "sudo bindfs --version | cut -d" " -f2" runs properly now.  This still leads to the same problem however

**Comment by merpmerp** [comment]
bindfs was installed from source with all the default options

**Comment by gael-ian** [comment]
Just released a new version of vagrant-bindfs. Please test if this one can correctly detect your bindfs version and use multithread.

**Comment by merpmerp** [comment]
I upgraded to the new plugin but it doesn't seem to resolve the problem
I commented out:
          if bindfs_version_lower_than("1.11")
            options.delete("multithreaded")
          end

Afterwards i saw the expected "--multithreaded" parameter on the bindfs command

I ran vagrant in debug mode and verified the output from your sudo command and it seems to be okay:
 INFO ssh: Execute: sudo -i bindfs --version | cut -d" " -f2 (sudo=false)
DEBUG ssh: stdout: 1.13.0

**Comment by merpmerp** [comment]
It looks like the value of bindfs_version is "0" after this command is executed (even though it succeeded and returned 1.13.0 on stdout) 
bindfs_version = @machine.communicate.execute(%{sudo -i bindfs --version | cut -d" " -f2});

**Comment by merpmerp** [comment]
Here is a patch that fixes the problem, it looks like the compare versions functionality was broken.
I fixed up the values for read/write rate as well
Also my ruby is terrible

diff --git a/lib/vagrant-bindfs/command.rb b/lib/vagrant-bindfs/command.rb
index 99fb81b..beb5010 100644
--- a/lib/vagrant-bindfs/command.rb
+++ b/lib/vagrant-bindfs/command.rb
@@ -112,8 +112,8 @@ module VagrantPlugins
             "xattr-rw"              => { long: ["xattr-rw"],                    short: [],    type: :flag,    default: false },
 
             # Rate limits
-            "read-rate"             => { long: ["read-rate"],                   short: [],    type: :option,  default: false },
-            "write-rate"            => { long: ["write-rate"],                  short: [],    type: :option,  default: false },
+            "read-rate"             => { long: ["read-rate"],                   short: [],    type: :option,  default: nil },
+            "write-rate"            => { long: ["write-rate"],                  short: [],    type: :option,  default: nil },
 
             # Miscellaneous
             "no-allow-other"        => { long: ["no-allow-other"],              short: ["n"], type: :flag,    default: false },
@@ -165,8 +165,10 @@ module VagrantPlugins
       
       def bindfs_version
         @bindfs_version ||= begin
-          bindfs_version = @machine.communicate.execute(%{sudo -i bindfs --version | cut -d" " -f2});
-          Gem::Version.new(bindfs_version)
+          @machine.communicate.execute(%{sudo -i bindfs --version | cut -d' ' -f2}) do |type, data|
+            bindfs_version = data.strip
+            return Gem::Version.new(bindfs_version)
+          end
         end
       end

**Comment by gael-ian** [comment]
I just release a 0.4.5 version of vagrant-bindfs, which should fix bindfs version detection.

Can you add ` local_ebweb1.bindfs.debug = true` to your Vagrantfile, run `VAGRANT_LOG=info vagrant up` and post here the output ?

**Comment by merpmerp** [comment]
There is a bug, have a look at my patch; it changes the default values of "read-rate" and "write-rate" to "nil"

Otherwise by default vagrant-bindfs will generate a command line with those two parameters set to "false"

 INFO interface: error: The bind command `bindfs --force-user=1500 --force-group=1500 --perms=u=rwx:g=rwx:o=rx --chown-ignore --chgrp-ignore --chmod-ignore --read-rate=false --write-rate=false --multithreaded -o noatime /mnt/src /src` failed to run!

Please check options values and compatibility. For a complete documentation,
run `sudo bindfs --help` on the VM.

You can see it online at http://bindfs.org/docs/bindfs.1.html
The bind command `bindfs --force-user=1500 --force-group=1500 --perms=u=rwx:g=rwx:o=rx --chown-ignore --chgrp-ignore --chmod-ignore --read-rate=false --write-rate=false --multithreaded -o noatime /mnt/src /src` failed to run!

Please check options values and compatibility. For a complete documentation,
run `sudo bindfs --help` on the VM.

You can see it online at http://bindfs.org/docs/bindfs.1.html

**Comment by gael-ian** [comment]
The original problem was on bindfs version detection. Can you add local_ebweb1.bindfs.debug = true to your Vagrantfile, run VAGRANT_LOG=info vagrant up and post here the output ?

I want to check if this now works with your specific use case.

**Comment by merpmerp** [comment]
Okay, here you are

[vagrant_bindfs.txt](https://github.com/gael-ian/vagrant-bindfs/files/47830/vagrant_bindfs.txt)

**Comment by gael-ian** [comment]
Ok, 0.4.6 had 2 missing options supported by bindfs 1.13 and fix rate limiting options default values. Thanks for pointing that.

What I don't understand is that detection seems to work on your VM with the original command. The `-i` option added to `sudo` is only used if the first detection fail and it never appears in your log. What if your remove the symlink you created /usr/local/bin/bindfs in /bin ?

**Comment by merpmerp** [comment]
0.4.6 looks good!

I'm not sure what thats about, this instance is based off of a newer version of the centos box file so the symlink is no longer there

I may have modified the default environment in the past week, although doing an interactive login (the -i sudo parameter) can be useful to make sure all necessary environment variables have been instantiated


Thanks much for all the help!

**Comment by gael-ian** [comment]
Thanks for your patience
