### ISSUE TITLE
Disable option

### ISSUE THREAD

**Issue by ggutenberg** [gael-ian/vagrant-bindfs#41]
What is the syntax for disabling an option?  Ex. you have `force-user` set to "vagrant" by default.  How do I disable `force-user` altogether?  I tried:

`config.bindfs.bind_folder "/var/www_tmp", "/var/www", force_user: nil, mirror: "@sysadmin", chown_ignore: true, chgrp_ignore: true, chmod_ignore: true, chmod_allow_x: true`

but that just threw a bunch of ruby errors when it tried to mount.

**Comment by gael-ian** [comment]
Ruby throws an error when trying to escape nil user and group names to check if they exist. This will be fixed in the next release that will be published today.

Sorry for being so long.
