### ISSUE TITLE
win10 vagrant use the bindfs have problem.

### ISSUE THREAD

**Issue by zerodeng1988** [gael-ian/vagrant-bindfs#45]
HI.I have some problem using vagrant-bindfs on win10.

My vagrangfile：
config.vm.synced_folder "D:/vagrant_share/", "/vagrant_data",type: :nfs
config.bindfs.bind_folder "D:/vagrant_db" ,"/vagrant_db",:owner => "mysql" ,:group => "mysql"

But,when i vagrant up ,it always  post this error:
default: Cannot bind source path D:/vagrant_db because it doesn't exist

Oh,i really sure that the dir is exist!

Need some help.....

**Comment by gael-ian** [comment]
Hi,

vagrant-bindfs can not bind directly an host directory in the guest VM. You have to share it first trought Vagrant synced_folder then rebind the guest mount point to another location inside the VM with permissions you want.

vagrant-bindfs README gives you [some usefull examples](https://github.com/gael-ian/vagrant-bindfs#example).

Hope this helps you.
