### ISSUE TITLE
Mirror lookup for source download

### ISSUE THREAD

**Issue by dripl** [gael-ian/vagrant-bindfs#46]
This plugin relies on http://bindfs.org/downloads/ as location for the library. At the moment the site is gone, domain is parked. I'm not aware of official mirrors.

https://github.com/gael-ian/vagrant-bindfs/blob/master/lib/vagrant-bindfs/cap/redhat/install_bindfs.rb

**Comment by dripl** [comment]
Got it to work, hacked install_bindfs.rb with http://pkgs.fedoraproject.org/repo/pkgs/bindfs/bindfs-1.13.0.tar.gz/67e1fc03f81c8c3a03703a6f4eef03d9/bindfs-1.13.0.tar.gz as download link.

bindfs.org is back online in the meanttime...

**Comment by dripl** [comment]
neat!

**Comment by gael-ian** [comment]
Sorry but I have to rollback to bindfs.org to download the sources tarball.

Github releases are just snapshots of the repository. Extracted sources require to call the [makerelease.sh](https://github.com/mpartel/bindfs/blob/master/releasescript/makerelease.sh) script to build a proper release and this have too many dependencies to taste me.

I'll open an issue for bindfs to ask if mirrors are a conceivable option.

**Comment by gael-ian** [comment]
Issue opened.
Wait and see

**Comment by gael-ian** [comment]
Mirrors may be set up in the future. As soon as they are alive, I will implement multiple lookups for tarball download when installing from source.

I leave this issue open as reminder.

**Comment by mpartel** [comment]
I've set up http://bindfs.dnsalias.net/ as an alias and contacted the DNS provider for support.

Sorry for taking this long to do it, I expected this to fix itself after some TTL somewhere expired, but it hasn't, though strangely the site does work from some ISPs.

**Comment by mpartel** [comment]
The domain should be [fixed now](https://github.com/mpartel/bindfs/issues/35#issuecomment-230328695)

**Comment by gael-ian** [comment]
Install script now checks bindfs.org and bindfs.dnsalias.net to download source tarball. If someday you set up an official mirror, please let me know to update [this list](https://github.com/gael-ian/vagrant-bindfs/blob/master/lib/vagrant-bindfs/version.rb#L7).

(I don't use archive.org as its url contains crawl date)

**Comment by mpartel** [comment]
Thanks, I'll keep that in mind.

(Turns out archive.org urls work even if you remove the date, e.g. https://web.archive.org/web/http://bindfs.org/downloads/bindfs-1.13.1.tar.gz works as long as the client can handle a 302. But it's probably impolite to point scripts at archive.org.)
