### ISSUE TITLE
How can I run something after the bind mounts are done

### ISSUE THREAD

**Issue by hanoii** [gael-ian/vagrant-bindfs#50]
I am provisioning a box with puphpet and I need to run something as soon as it's up, but after the bindfs mounts are setup, is there a way to do that?

**Comment by gael-ian** [comment]
Hi,

The bindfs mounts usually executed just after the shared folders mounts when a VM starts. Provisionning, with any provider, should happen later by default.

So either I don't understand your question and then please excuse me or I need to see more of your setup to be able to help you. Can you add a gist with your Vagrantfile and maybe some details on the context ?

Thanks.

**Comment by gael-ian** [comment]
I suppose this problem as been resolved...
