### ISSUE TITLE
multiples user:group in a single synced folder

### ISSUE THREAD

**Issue by jujes** [gael-ian/vagrant-bindfs#51]
Hi, someone know how config bindfs to keep **multiples user:group in a single synced folder**?
in my case: /home/vagrant/dpl
**here my work environment**

* OS

```
host ubuntu 16.04
guest ubuntu 16.04
```

* vagrant plugins

```
vagrant-vbguest
vagrant-bindfs
```
* Vagrantfile

```
...
config.vm.synced_folder "../dpl", "/home/vagrant/sync", type: :nfs
config.bindfs.bind_folder "/home/vagrant/sync", "/home/vagrant/dpl",
....
```
* virtual exchange

```
virtualbox > vagrant > docker
docker create multiple user:groups as it need...
```

* users:groups working on /home/vagrant/dpl

```
main
root:root

mysql
vboxadd:vboxsf

content
www-data:www-data
```
thanks in advance,

**Comment by gael-ian** [comment]
Hi,

I never encounter this kind of problem before but Linux ACL looks like a way to deal with it. It seems that Fuse supports them and so bindfs (_via_ the '-o' argument) but you'll have to try to be sure.

I close this issue as it's not related to `vagrant-bindfs`. It's more a sysadmin problem.

Thanks.
