### ISSUE TITLE
Composer installer fails

### ISSUE THREAD

**Issue by kevinsperrine** [gael-ian/vagrant-bindfs#52]
I originally opened this on the composer/installers repo, but turns out it's _something_ happening in bindfs. I have no idea exactly as I don't know where/how to get log files for bindfs errors. When using bindfs version 1.13.2 on the guest machine (redhat variety linux) I ran into an issue where composer/installers would simply fail to install. I realized it would work when the vagrant-bindfs plugin wasn't active, so I took a shot at simply upgrading the bind version to from 1.13.2 to 1.13.4 and lo-and-behold it works now. I'm happy to try and debug more if you want. You can see the composer output on the other issue if interested. If not, it might be a good idea to bump the bindfs version installed on redhat machines (when installed from source).

https://github.com/composer/installers/issues/331

**Comment by mpartel** [comment]
Most likely https://github.com/mpartel/bindfs/issues/41 which was introduced in 1.13.1 and fixed in 1.13.4. Sorry about that :/

**Comment by kevinsperrine** [comment]
You're probably right. Don't worry about it. Thanks for the great plugin!

**Comment by gael-ian** [comment]
Hi,

I updated the plugin to use bindfs 1.13.4 when it have to be compiled from the sources (as on some Red Hat flavours) so you won't have to upgrade it by hand anymore. For packages installations, I trust the distro maintainers to do their job well.

Without this issue, I wouldn't have noticed new releases of bindfs before long. Thanks for reporting, Kevin, even for a non-problem ;) I will now be notified of all future releases (via sibbell.com) and shall be able to react more quickly to this kind of problem and to new options to be supported.

A new version of vagrant-bindfs should be released in minutes.
