### ISSUE TITLE
Allow SOURCE_VERSION to be configurable

### ISSUE THREAD

**Issue by jeffgeorge** [gael-ian/vagrant-bindfs#54]
Hi @gael-ian, 

My team loves and heavily depends on your vagrant plugin, but recently we tripped over an issue regarding `bindfs` Upstream Dependencies. Short version, `vagrant-bindfs` depends on specific hard-coded versions of `bindfs`, as defined in [version.rb](https://github.com/gael-ian/vagrant-bindfs/blob/master/lib/vagrant-bindfs/version.rb). `bindfs` itself depends on FUSE, and newer versions of FUSE depend on newer versions of ruby and, well, dependency hell.

It would be super super helpful if `vagrant-bindfs` would just let me optionally peg a specific version of `bindfs` to go grab, falling back to whatever you've hardcoded to.

I can see two benefits here:
- This would let me peg a specific version I *know* isn't going to result in dependency issues.
- Similarly, this would let me test newer versions of `bindfs` without having to wait for you to push a new build of `vagrant-bindfs`

**Comment by gael-ian** [comment]
Hi Jeff,

The version number of the source tarball used when bindfs has to be installed from source is now configurable trough `config.bindfs.source_version`.

This will only work for distributions part of the Red Hat family and only when bindfs can't be installed from a repository. I leave this issue open as a reminder to :

* Add an option to force bindfs installation from source
* Try to get the requested version from repositories when available

I have some refactoring in progress for the next releases of the plugin. This should be included in the roadmap.

**Comment by gael-ian** [comment]
Hi @jeffgeorge 

After some more work and a large refactoring, a 1.0.0 version of bindfs that support installation of a precise version of bindfs for every OSes is almost ready to be released.

Before pushing it in the wild, can you please test it and see if it fits your needs ?

Thanks

**Comment by gael-ian** [comment]
1.0.0 has been released.
