### ISSUE TITLE
Bundler causing issues with bindfs install?

### ISSUE THREAD

**Issue by MikePadge** [gael-ian/vagrant-bindfs#56]
I've been beating up against this for a day or so, and I'm not even sure if I'm in the right place. This appears to only occur while trying to install the bindfs plugin.

the error I keep getting is 

```
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing vagrant-bindfs (0.4.12), and Bundler cannot continue.
Make sure that `gem install vagrant-bindfs -v '0.4.12'` succeeds before bundling.

Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.Gem::InstallError: vagrant-bindfs requires Ruby version ~> 2.0.0.

```

EDIT:TLDR for anyone who stumbles here- "vagrant plugin install vagrant-bindfs --plugin-version '0.4.11'"
fixes this if you're trying to get past this error for a vagrant up

Vagrant 1.8.7 - reverted to 1.8.6 because of current curl issues
Bundler version 1.12.5
ansible 2.0.2.0
osx 10.12.1
ruby 2.3.2

gem install vagrant-bindfs -v '0.4.12' 

fails with

ERROR:  Error installing vagrant-bindfs:
	vagrant-bindfs requires Ruby version ~> 2.0.0.

As noted, I'm using Ruby 2.3.2

disabling multisource fails as well (I've cleared my gem cache and cleaned my gems up as well)

Also found this as scheduled for the next release of vagrant
core: Remove Bundler integration for handling internal plugins [GH-7793, GH-8000, GH-8011]

annd your tweet about Rubygems/bundler merging. 

:P lelz, I feel like I may have just gotten caught in a limbo period with this. Still wanted to go ahead and give you the heads up though in case you weren't already aware.

**Comment by inthedeepend** [comment]
+1

**Comment by flocca** [comment]
+1

**Comment by inthedeepend** [comment]
Any chance we can fix this up asap or get access to an older version somehow... quite disruptive :)

**Comment by MikePadge** [comment]
@inthedeepend this currently works

vagrant plugin install vagrant-bindfs --plugin-version '0.4.11'

**Comment by gael-ian** [comment]
Hi,

This issue was introduced by [this commit](https://github.com/gael-ian/vagrant-bindfs/commit/d5d88994a0882630a68b66a44c44666a7ada4118), part of the last release. It was supposed to fix a compatibility problem with older versions of Vagrant but I should have used a '>= 2.0.0' requirement or just removed it, as there is no code in the plugin that really rely on any new thing introduced in Ruby since 1.9.3.

I can fix it easily but only in a few days (6 or so), as I'm far away from any computer for the moment.

Sorry for the inconvenience.
For the next days, you can use the solution proposed by @MikePadge

**Comment by gael-ian** [comment]
Thanks to @renan, the fix is now in master but I can't push a new release of the gem from my smartphone.

(Maybe @igor47 can do it ?)

**Comment by gael-ian** [comment]
vagrant-bindfs 0.4.13 has been released a few minutes ago.
Thanks for your patience and contributions.
