### ISSUE TITLE
Error installing vagrant-bindfs

### ISSUE THREAD

**Issue by mattmaker** [gael-ian/vagrant-bindfs#58]
I ran the command **vagrant plugin install vagrant-bindfs** in my terminal and got the following error:

```
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing vagrant-bindfs (0.4.12), and Bundler cannot continue.
Make sure that `gem install vagrant-bindfs -v '0.4.12'` succeeds before bundling.

Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.Gem::InstallError: vagrant-bindfs requires Ruby version ~> 2.0.0.
```
After that, I ran the command in the error: **gem install vagrant-bindfs -v '0.4.12'** and got this error:
```
ERROR:  Error installing vagrant-bindfs:
	vagrant-bindfs requires Ruby version ~> 2.0.0.
```

I used **ruby -v** and it said `ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]`

It seems that I have a version of Ruby that is higher than what it's asking for. What should I do to fix this?

**Comment by bsdnomad** [comment]
Same here, temporary solution is to use the previous version:

`sudo vagrant plugin install vagrant-bindfs --verbose --plugin-version 0.4.11`

**Comment by gael-ian** [comment]
Hi,

This is the same problem as discussed in #56. The solution has been found and will be released as soon as possible.

Thanks
