### ISSUE TITLE
Ignore files with bindfs

### ISSUE THREAD

**Issue by lifeiscontent** [gael-ian/vagrant-bindfs#59]
Hi, I was wondering if there is an option to sync a folder, but ignore certain files such as `.vagrant`  and `node_modules` dir

**Comment by mpartel** [comment]
[bindfs](https://github.com/mpartel/bindfs) does not currently have such an option. I'd be happy to accept a PR for that as long as it handles all cases, including write attempts etc.

**Comment by gael-ian** [comment]
You can [use rsync](https://www.vagrantup.com/docs/synced-folders/rsync.html) to sync directories between host and guest machines. It supports an `exclude` option that may be a solution to your need.
