### ISSUE TITLE
vagrant up does not start, SOURCE_VERSION error 

### ISSUE THREAD

**Issue by laurynasant** [gael-ian/vagrant-bindfs#60]
Just installed vagranf-bindfs with a fresh installation of vagrant. Vagrant up does not start due to an error with SOURCE_VERSION. Error information below:

```
/.vagrant.d/gems/gems/vagrant-bindfs-0.4.13/lib/vagrant-bindfs/config.rb:56:in `finalize!': uninitialized constant VagrantPlugins::Bindfs::SOURCE_VERSION (NameError)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/config/v2/root.rb:50:in `block in finalize!'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/config/v2/root.rb:49:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/config/v2/root.rb:49:in `finalize!'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/config/v2/loader.rb:21:in `finalize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/config/loader.rb:168:in `load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/vagrantfile.rb:28:in `initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/environment.rb:746:in `new'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/environment.rb:746:in `vagrantfile'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/environment.rb:492:in `host'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/environment.rb:214:in `block in action_runner'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/runner.rb:33:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/runner.rb:33:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/environment.rb:479:in `hook'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/environment.rb:728:in `unload'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/bin/vagrant:192:in `ensure in <main>'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/bin/vagrant:192:in `<main>'
```

**Comment by rbngzlv** [comment]
Hi!

Downgrading to version `0.4.11` solved the problem for me. 

```sh
vagrant plugin uninstall vagrant-bindfs
vagrant plugin install vagrant-bindfs --plugin-version 0.4.11
```

**Comment by chronon** [comment]
With the current release `0.4.13` I get the same error as above. With `0.4.12` the plugin will not install with a plugin bundler error (Warning: this Gemfile contains multiple primary sources, etc.). Reverting to `0.4.11` works for me as well.

**Comment by laurynasant** [comment]
Yes, same errors as @chronon . `0.4.11` version works only.

**Comment by Artistan** [comment]
same error here with 0.4.13

`➜  test vagrant up
/Users/cpeterson/.vagrant.d/gems/gems/vagrant-bindfs-0.4.13/lib/vagrant-bindfs/config.rb:56:in `finalize!': uninitialized constant VagrantPlugins::Bindfs::SOURCE_VERSION (NameError)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/config/v2/root.rb:50:in `block in finalize!'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/config/v2/root.rb:49:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/config/v2/root.rb:49:in `finalize!'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/config/v2/loader.rb:21:in `finalize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/config/loader.rb:168:in `load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/vagrantfile.rb:28:in `initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/environment.rb:746:in `new'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/environment.rb:746:in `vagrantfile'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/environment.rb:492:in `host'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/environment.rb:214:in `block in action_runner'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/runner.rb:33:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/runner.rb:33:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/environment.rb:479:in `hook'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/environment.rb:728:in `unload'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/bin/vagrant:192:in `ensure in <main>'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/bin/vagrant:192:in `<main>'`

**Comment by gael-ian** [comment]
v0.4.14 should fix this issue. Thanks to @rbngzlv
