### ISSUE TITLE
bindfs not available through sudo

### ISSUE THREAD

**Issue by francoisjacques** [gael-ian/vagrant-bindfs#64]
Hello!

I've been trying to use your plugin on a `CentOS release 6.7 (Final)` VM. First some context, I absolutely had to install `bindfs` through the sources as `yum` couldn't find `bindfs` through the standard repositories. It was really nice to find such feature (good job!). It got installed in the standard location as expected, e.g. `/usr/local/bin`

Now it seems like the `bindfs` validation appears broken a bit. It did detect `bindfs` correctly through `bindfs --help` when running as standard vagrant user but failed to execute it through `sudo`.

First validation snippet from `vagrant` debug log:

```
INFO ssh: Execute: bindfs --help (sudo=false)
DEBUG ssh: stdout: 
Usage: bindfs [options] dir mountpoint
(... abridged ...)

DEBUG ssh: Exit status: 0
```

Next excerpt, exposing the problem. The `sudo` session can't reach `bindfs` and the plugin fails to detect that problem:

```
DEBUG ssh: Checking whether SSH is ready...
DEBUG ssh: Re-using SSH connection.
 INFO ssh: SSH is ready!
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute:  (sudo=false)
DEBUG ssh: Exit status: 0
DEBUG guest: Searching for cap: bindfs_bindfs_version
DEBUG guest: Checking in: redhat
DEBUG guest: Checking in: linux
DEBUG guest: Found cap: bindfs_bindfs_version in linux
 INFO guest: Execute capability: bindfs_bindfs_version [#<Vagrant::Machine: master (VagrantPlugins::ProviderVirtualBox::Provider)>] (redhat)
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: sudo bindfs --version | cut -d" " -f2 (sudo=false)
DEBUG ssh: stderr: sudo
DEBUG ssh: stderr: : 
DEBUG ssh: stderr: bindfs: command not found
DEBUG ssh: stderr: 

DEBUG ssh: Exit status: 0
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: sudo -i bindfs --version | cut -d" " -f2 (sudo=false)
DEBUG ssh: stderr: -bash: bindfs: command not found

DEBUG ssh: Exit status: 0
 INFO interface: detail: Bindfs 0.0 is installed
 INFO interface: detail:     master: Bindfs 0.0 is installed
    master: Bindfs 0.0 is installed
```

Perhaps that should be used instead (notice the `'`s) !

```
sudo -i 'bindfs --version | cut -d" " -f2'
```

Example:

```
[blah@vm vagrant]$ sudo bindfs --version | cut -d" " -f2
sudo: bindfs: command not found
[blah@vm vagrant]$ echo $?
0
[blah@vm vagrant]$ sudo 'bindfs --version | cut -d" " -f2'
sudo: bindfs --version | cut -d" " -f2: command not found
[blah@vm vagrant]$ echo $?
1
````

Also, considering that obviously bindfs will fail in this context, I think it would be worth retrieve the full path and invoke it with the full path in the sudo session

```
[blah@vm vagrant]$ type bindfs
bindfs is /usr/local/bin/bindfs
```

Thank you a lot for this plugin!
- François

**Comment by gael-ian** [comment]
Hi @francoisjacques 

I just released a new version of the plugin that always use the full path of the bindfs binary. This should fix your problem but, if not, feel free to reopen this issue (and add a copy of your Vagrantfile so I can test with the exact same box as you).

Thank you for reporting

**Comment by francoisjacques** [comment]
Merci beaucoup @gael-ian !
