### ISSUE TITLE
Unable to disable options `--force-user`, `--force-group`, and `--perms`

### ISSUE THREAD

**Issue by rrei** [gael-ian/vagrant-bindfs#70]
Hi, first of all thank you for making this great plugin ;)

In the latest version I'm unable to disable some options by passing in `nil` as the value. I've taken a look at the source and it seems to me that `VagrantBindfs::Bindfs::OptionSet.cast_option_as_value` is converting the `nil` values to empty strings, therefore those options are passed to the actual bindfs command instead of being disabled.
Do you provide any other way to disable options?
Thanks

**Comment by gael-ian** [comment]
Hi @rrei 

Sorry, there's no other way to disable these options but this obviously sounds like a bug. I should be able to fix it before the end of the week-end.

Thanks for reporting

**Comment by rrei** [comment]
Great news @gael-ian! I'll be updating to the latest version as soon as this is fixed :)
I really need to be able to disable certain defaults for the project I'm working on.
Glad I could help, if only a tiny bit ;)

**Comment by rrei** [comment]
Great, thanks a lot! ;) I've already tested the new version on my project and it works like a charm :dancing_men:

**Comment by gael-ian** [comment]
You're welcome ;o)
