### ISSUE TITLE
Question: bindfs with non-existing user

### ISSUE THREAD

**Issue by iongion** [gael-ian/vagrant-bindfs#71]
How can this be achieved ?
- I have user `app` and want to mount `/vagrant` into `/home/app/runtime`
- Bindfs applies at boot, so I cannot create it before

**Comment by gael-ian** [comment]
Hi @iongion

You can use [one of the Vagrant provisioning options](https://www.vagrantup.com/docs/provisioning/index.html) to create your `app` user and delay binding of your folder after provisioning passing an `:after` option to the `bind_folder` method.

    config.bindfs.bind_folder "/vagrant", "/home/app/runtime", after: :provision

All supported options for the `bind_folder` method are described in [the Usage section of the README](https://github.com/gael-ian/vagrant-bindfs/blob/master/README.md#usage).

Hope this helps you. Don't hesitate to reopen this issue if you need more explanations.

**Comment by iongion** [comment]
Excelent @gael-ian , thank you!!!
