### ISSUE TITLE
Force owner and group for a specify directory

### ISSUE THREAD

**Issue by tux240** [gael-ian/vagrant-bindfs#73]
Hello,

Is it possible to force an owner and group to a specific repertory ?
I have many folders and I would like my symfony project get main-api.
Actually I have vagrant in each folders and get permission denied during my docker-compose up

Thanks for your help

**Comment by gael-ian** [comment]
Hello @tux240 

You lucky, this is exactly what this plugin is made for! Just have a look [at the README](https://github.com/gael-ian/vagrant-bindfs#installation) for explanations about how it works and you'll be able to set, per directory, user, group and permissions you need.

Feel free to ask if you don't understand something.

**Comment by tux240** [comment]
Thanks for your answer !
And is it possible to exclude some files or folders or I have to create each line by folder/file to mount ? thanks

**Comment by gael-ian** [comment]
Just as a shared folder make the whole underlying arborescense available in the guest machine, binding affect a folder and all its children and apply the same user, group and permissions.

Different folder can have different settings, of course.
