### ISSUE TITLE
Gentoo support

### ISSUE THREAD

**Issue by omakogon** [gael-ian/vagrant-bindfs#78]
Hello,

I'm trying to use bindfs for my guest machine Gentoo.

$cat /etc/gentoo-release
Gentoo Base System release 2.3

I get an error when running the vagrant up command:

Checking for bindfs in VM...
Vagrant attempted to execute the capability 'bindfs_package_manager_name'
on the detect guest OS 'gentoo', but the guest doesn't
support that capability. This capability is required for your
configuration of Vagrant. Please either reconfigure Vagrant to
avoid this capability or fix the issue by creating the capability.

Do you plan to add support for Gentoo in the new version of your wonderful plug-in?

Thanks

**Comment by gael-ian** [comment]
Hi @omakogon,

If I can find a reliable and regularly updated Gentoo base box to [use in tests](https://github.com/gael-ian/vagrant-bindfs/blob/master/Vagrantfile#L20), I would be happy to support that distro (even if I never used it so it may take me some time to figure out everything I need).

Sadly, the last time I checked, there was no official Gentoo box from HashiCorp or the Bento project. Some exist on VagrantCloud but I don't anything about how the are supported.

If you're confident with Gentoo and know a reliable box, the pull requests are always open :)
