### ISSUE TITLE
Source path doesn't exist error

### ISSUE THREAD

**Issue by wturrell** [gael-ian/vagrant-bindfs#79]
This line:

    config.bindfs.bind_folder '/Users/wt/vm/wordpress-vvv2/www/', '/srv/www/', :owner => "www-data", :mount_options => [ "dmode=775", "fmode=774" ]

is giving me the following error on `vagrant up`:

    Cannot create bind mount from '/Users/wt/vm/wordpress-vvv2/www/' to '/srv/www/': Source path '/Users/wt/vm/wordpress-vvv2/www/' doesn't exist

However that directory definitely _does_ exist.   I originally attempted it with `www/` as the source, which gave me a warning that the path needs to be absolute.

I've tested with Vagrant 1.9.2 and 2.0.0, Virtualbox 5.1.28 on Mac OSX 10.12.6 (Sierra) using [WordPress VVV](https://github.com/Varying-Vagrant-Vagrants/VVV) version 2.   The box has the latest guest additions.

Any ideas?  (I have also tried it with the options removed, as I realise I may not have the correct syntax.)

**Comment by gael-ian** [comment]
Hi @wturrell,

I confirm that :mount_options is not supported by `vagrant-bindfs` and advise you to get a closer look at its [README](https://github.com/gael-ian/vagrant-bindfs/blob/master/README.md) for the exact syntax.

However, if the directory exists, you should not get this error message. Are you sure there's no differences between the actual path and the one you set in your Vagrantfile, not even in its case ? Some Mac OS filesystem's are case-sensitive, which is a good thing but can lead to typos.

What version of `vagrant-bindfs` do you use ? Can you paste here your whole Vagrantfile and the output of a `ls -al '/Users/wt/vm/wordpress-vvv2/www/'` ?

Thanks

**Comment by wturrell** [comment]
Hello. The vagrant-bindfs plugin is version 1.0.9. 
Here are the directory listings:

```
$ ls -al '/Users/wt/vm/wordpress-vvv2/www/'
total 0
drwxr-xr-x   7 wt  staff  238 10 Oct 13:39 .
drwxr-xr-x  19 wt  staff  646 12 Oct 16:31 ..
drwxr-xr-x   8 wt  staff  272  2 Oct 13:48 default
drwxr-xr-x  22 wt  staff  748 10 Oct 13:43 phpcs
drwxr-xr-x   7 wt  staff  238  2 Oct 13:48 wordpress-default
drwxr-xr-x   8 wt  staff  272  2 Oct 13:50 wordpress-develop

$ ls -ld '/Users/wt/vm/wordpress-vvv2/www/'
drwxr-xr-x  7 wt  staff  238 10 Oct 13:39 /Users/wt/vm/wordpress-vvv2/www/
```

I was just looking at the [source code](https://github.com/gael-ian/vagrant-bindfs/blob/1c66bf1f59f4b888f6cdfb7c6e8192c76fde181f/lib/vagrant-bindfs/bindfs/validators/runtime.rb#L19), if I run the ruby command manually it seems OK:

```
irb(main):001:0> File.directory?("/Users/wt/vm/wordpress-vvv2/www/")
=> true
```
(NB: I have only been learning Ruby for 10 minutes…)

Let me know if you still need the full Vagrantfile - it's basically this with minimal changes, including the `config.bindfs.bind_folder` line of course.

**Comment by gael-ian** [comment]
Hi @wturrell, 

Sorry, I've been reading too fast yesterday to clearly understand your problem.

The `bind_folder` method allows you to re-mount a directory of the guest machine in another location, with different owner, group, permissions, etc. It does nothing to share an host directory with the guest machine.

In order to do what you want, you have to first share the '/Users/wt/vm/wordpress-vvv2/www/' with the guest machine and then bind it to another location, i.e. with:

    config.vm.synced_folder '/Users/wt/vm/wordpress-vvv2/www/', '/home/vagrant/www/'
    config.bindfs.bind_folder '/home/vagrant/www/', '/srv/www/', :user => "www-data"

Again, I invite you to read [`vagrant-bindfs` README](https://github.com/gael-ian/vagrant-bindfs/blob/master/README.md) for more information on use and syntax.

Thanks
