### ISSUE TITLE
Conflicting dependencies for `json`

### ISSUE THREAD

**Issue by KnightHawk3** [gael-ian/vagrant-bindfs#80]
I am unable to install this on the latest debian testing (buster)

```bash
melody@earth ~/D/k/trellis> vagrant plugin install vagrant-bindfs
Installing the 'vagrant-bindfs' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

conflicting dependencies json (= 1.8.3) and json (= 2.1.0)
  Activated json-2.1.0
  which does not match conflicting dependency (= 1.8.3)

  Conflicting dependency chains:
    json (= 2.1.0), 2.1.0 activated

  versus:
    json (= 1.8.3)

  Gems matching json (= 1.8.3):
    json-1.8.3
```

I can't seem to find anything about this error sorry, any assistance?

**Comment by gael-ian** [comment]
Hi @KnightHawk3,

There's no dependency between vagrant-bindfs ans json so I guess this problem is related to [hashicorp/vagrant#8978](https://github.com/hashicorp/vagrant/issues/8978).

People at Hashicorp are still working on, but you can use the same workaround as in issues #76 and #77: uninstall Vagrant, remove your `~/.vagrant` directory and reinstall it.

Hope this helps,

Gaël-Ian

**Comment by KnightHawk3** [comment]
Thanks! Sorry I couldn't work out what was causing it!

**Comment by gael-ian** [comment]
I'd like to find it too as you're not the first one who suffers it, but it seems to have its roots deep in a proprietary plugin only Hashicorp can look at :/

Glad the workaround was enough for you !

**Comment by seankibler** [comment]
I had a similar issue but with a version conflict for other gems, starting with ffi gem. After an evening of hair pulling it was evident the Ruby env embedded in `/opt/vagrant` was not sane. What worked was manually uninstalling vagrant (https://www.vagrantup.com/docs/installation/uninstallation.html) and remove `~/.vagrant.d` (make a backup! at least of your boxes!). Then run the 2.0.1 installer. After that I had a fresh and functional vagrant environment. Restored my boxes, installed plugins I needed and once again all was good in the world.
