### ISSUE TITLE
Is vagrant-bindfs required/useful while running windows hosts and winnfsd?

### ISSUE THREAD

**Issue by Hlsgs** [gael-ian/vagrant-bindfs#81]
Please excuse the n00bish question. Thank you!

**Comment by gael-ian** [comment]
Hello,

vagrant-bindfs is no more required to use winnfsd than to use any other NFS server. However, as NFS is not built to handle them and will probably never, you may encounter just the same guest-side permissions issues this plugin help to solve.

Feel free to reopen this issue if you have more questions.

**Comment by Hlsgs** [comment]
Thanks for the prompt answer. I guess the question was if, considering Windows' permission system, those issues still apply or if they are only a Mac/Linux thing.

**Comment by gael-ian** [comment]
I never tried but, as the problem sits on guest side, I suppose it will be the same whatever the host OS is. You can try without vagrant-bindfs and just remember it may give you the solution you need if somethings wrong.

**Comment by Hlsgs** [comment]
I've actually been using PuPHPet with winnfsd on Windows 10 without issues for more than a year. Now I've installed vagrant-bindfs and PHPMyAdmin is no longer able to access it's "tmp" folder. I will revert back and keep your advice in mind. Thank you again!

**Comment by gael-ian** [comment]
I don't think the two are related. vagrant-bindfs does absolutely nothing until you explicitly set bindings in your Vagrantfile (See README for syntax and options). If you did nothing more than install the plugin, there should be no problem.

If you tried to use bindfs to change permissions on the PHPMyAdmin directories then you can post your Vagrantfile and more about your setup and I may be able to help you.
