### ISSUE TITLE
Conflicting dependencies fog-core 

### ISSUE THREAD

**Issue by explorier** [gael-ian/vagrant-bindfs#82]
Hi, I'm trying to install vagrant-bindfs on Ubuntu 18.04, with Vagrant 2.02, and getting this error:

```
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

conflicting dependencies fog-core (~> 1.43.0) and fog-core (= 1.45.0)
  Activated fog-core-1.45.0
  which does not match conflicting dependency (~> 1.43.0)

  Conflicting dependency chains:
    fog-core (= 1.45.0), 1.45.0 activated

  versus:
    vagrant-libvirt (> 0), 0.0.41 activated, depends on
    fog-core (~> 1.43.0)
```

Not sure what to do here. Thanks for any help!

**Comment by explorier** [comment]
Oops, should have tried this first, didn't realize Ubuntu's binary was outdated - just installed Vagrant 2.1.1 and vagrant-bindfs installed fine.

**Comment by gael-ian** [comment]
Hi,

Glad it's fixed, as `vagrant-bindfs` does not have any dependencies so I would have had some trouble to help you :)
