### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by adi-** [gael-ian/vagrant-bindfs#85]
Have a problem with `guest/mount/point`. When I am checking permissions on that folder I have `vagrant:vagrant`. But when I check those permissions on `..` inside `guest/mount/point` I get `root:root`. Any chance to fix `..` permissions or am I missing something?

**Comment by gael-ian** [comment]
Hello,

bindfs sets "virtual" owner, group and permissions only from the mount point and its content but does not go upward.

If you want to change one of these on an upper directory, you can either use chmod/chown or set a mount point closer to your filesystem's root.

What exactly are you trying to do ?

**Comment by adi-** [comment]
I understand and I do exactly as you proposed. I just thought there is a built in option to allow user to go `up` one level (`..`). Merry Christmas @gael-ian!

**Comment by gael-ian** [comment]
You're welcome. Merry Christmas too :)
