### ISSUE TITLE
Action triggers for bindfs events

### ISSUE THREAD

**Issue by robertnisipeanu** [gael-ian/vagrant-bindfs#95]
Is there a way to hook actions from the bindfs plugin? I want to create a (source) directory before executing the bindfs. I tried hooking to the `VagrandBindfs::Vagrant::Actions::Mounter` action, however it seems that the trigger is never called. Running bindfs after provisioning and creating the directory in provision is not a solution as the provisioning scripts already assumes the link exists

**Comment by gael-ian** [comment]
Hi @robertnisipeanu,

Sorry for the late answer. Currently there's no way to hook into vagrant-bindfs actions and, as vagrant has its own hooks system, integrating one sounds like an overkill. However, I understand you have a very specific use case that might hint in that direction, although I don't really understand what you are trying to do.

Maybe it can be done another way:

- Can you build and fill the directory from your provisioning script and let bindfs mount it somewhere else afterward?
- Can you use [one of Vagrant's actions](https://www.vagrantup.com/docs/plugins/action-hooks) to hook a micro-plugin just to create your directory?
- Can you use another directory you know already exist? ($HOME?)

bindfs and fuse themselves do not seem to have an option to automatically create the source directory if it doesn't exist.

**Comment by robertnisipeanu** [comment]
Hi @gael-ian 

Use case it so use Unison (rsync like, but two-way synchronization) instead of NFS as NFS becomes slow when it has to deal with a lot of small files. The provision files of the vagrant box (there are quite a few) needs access to the symlink created by bindfs, so I need to create the bindfs before the provision scripts run, so I can't create the folders in provision before bindfs runs. I was curious if bindfs has an action that I can hook up before it binds as I could have used that to create the source directory, which would be easier than any other alternatives.

I tried hooking into vagrant actions, but seems that none of them runs after VM is booted and before synced_folders/bindfs. All of them run either before boot, right after boot (where ssh can't yet execute, so execute-remote is not available), or after bindfs runs.

Will look into creating a micro-plugin, maybe that can help me.

As there are no plans to integrate a hook system (haven't looked on how vagrant handles those, I thought they have a hook system and any plugin can expose actions, but if this is not the case, then yes, it's an overkill to create another one for the bindfs plugin) I think this issue can be closed.
